version: '3.6'

services:
  mongo:
    container_name: docker-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    hostname: mongo

  spring:
    depends_on:
      - mongo
    image: instantmessenger:latest
    ports:
      - "8080:8080"
      - "9999:9999"
    hostname: spring
    links:
      - mongo
    environment:
      - DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9999
volumes:
  mongodata: