version: '2.1'

services:
  mongo:
    container_name: docker-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/zenbrain --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    hostname: mongo

  spring:
    depends_on:
      mongo:
        condition: service_healthy
    image: instantmessenger:latest
    ports:
      - "8080:8080"
      - "9999:9999"
    hostname: spring
    links:
      - mongo
    environment:
      - DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9999
    #todo add health check for mongo